name: Build Debug

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Cospylet platform
          os: windows-latest

        - name: Android 64/2
          os: ubuntu-latest
          target: Android32

        - name: Android64 my beloved
          os: ubuntu-latest
          target: Android64

        - name: MacOS for the -4 users
          os: macos-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}
  build-ios:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Catch up
        # see https://github.com/actions/checkout/issues/439
        run: git pull origin main --no-rebase

      - name: iOS 🤫
        uses: geode-catgirls/build-geode-mod@main
        with:
          bindings: geode-catgirls/bindings
          target: iOS
          gh-pat: ${{ secrets.GH_PAT }}
  package:
    name: Package builds
    runs-on: ubuntu-latest
    # if: success() || failure()
    needs: ['build']
    steps:
      - uses: geode-catgirls/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
  check_and_upload:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Check if Build Output.zip was uploaded
        run: |
          if [[ "${{ needs.package.outputs.build-output }}" ]]; then
            echo "Build Output.zip was uploaded successfully."
          else
            echo "Build Output.zip was not uploaded."
          fi
